### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by vfalconi** [vfalconi/web-terminal#2]
- [ ] CLI focus on page load
- [ ] fix weird font thing where CLI is different from buffer (somehow)
- [ ] create response classes
